# Generated by Django 4.2.11 on 2025-01-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
